### ISSUE TITLE
下载m3u8文件时显示Error in reading file

### ISSUE THREAD

**Issue by AdorableStar** [cildhdi/wm#3]
当使用N_m3u8DL-CLI下载时 显示Error in reading file
![image](https://user-images.githubusercontent.com/30179706/83761215-99024200-a6a8-11ea-9338-995d58837527.png)

**Comment by CGZ127** [comment]
同样的问题，在填入请求头后一样，simpleG 20200417，cli是2.6.3，查看meta.json感觉没问题，每个ts的网址都有
https://drive.google.com/file/d/17R9LYHH6PBHuj3XTD0Im9pmy-VcomZ2J/view?usp=sharing
https://drive.google.com/file/d/1Xp_uqZ-i9w3uhMqWnqy6uwb4EHpOOUtY/view?usp=sharing
上面两个是json文件和m3u8文件

**Comment by cildhdi** [comment]
> 同样的问题，在填入请求头后一样，simpleG 20200417，cli是2.6.3，查看meta.json感觉没问题，每个ts的网址都有
> https://drive.google.com/file/d/17R9LYHH6PBHuj3XTD0Im9pmy-VcomZ2J/view?usp=sharing
> https://drive.google.com/file/d/1Xp_uqZ-i9w3uhMqWnqy6uwb4EHpOOUtY/view?usp=sharing
> 上面两个是json文件和m3u8文件

@CGZ127  可以把课程链接贴一下我看看吗

**Comment by CGZ127** [comment]
https://www.nfmovies.com/video/?50097-2-6.html，开了反爬比较麻烦，我都是用手机via浏览器资源嗅探到的m3u8

**Comment by cildhdi** [comment]
@CGZ127 抱歉我没法提供实际上的帮助，这个网址不是万门课程的链接，并且我点进去需要登录才可以查看相关内容。你可以在 Network 调试页面观察网页对 ` *.ts ` 的请求中的 Header 部分，找出那些必须的项填入请求头。

**Comment by lyjsly** [comment]
购买的课程给你看看，无法下载。步骤都按照你的来的
能私信吗，课程不是公开的

**Comment by AdorableStar** [comment]
![image](https://user-images.githubusercontent.com/30179706/84852197-caa6e000-b08e-11ea-94d1-e2f03d33d7d7.png)
某些爬取到的文件内容如图，内容不是*.ts

**Comment by AdorableStar** [comment]
![image](https://user-images.githubusercontent.com/30179706/84852339-2709ff80-b08f-11ea-9cdf-f143f2c70221.png)
大部分爬取到的.m3u8文件内容如图，内容并不是*.ts。导致下载不了

**Comment by cildhdi** [comment]
@AdorableStar 前几天更新了脚本，再试试看呢？

**Comment by AdorableStar** [comment]
> @AdorableStar 前几天更新了脚本，再试试看呢？

请问Release里面的.exe文件是已经更新的么

**Comment by cildhdi** [comment]
> > @AdorableStar 前几天更新了脚本，再试试看呢？
> 
> 请问Release里面的.exe文件是已经更新的么

exe 无需更新

**Comment by AdorableStar** [comment]
> > > @AdorableStar 前几天更新了脚本，再试试看呢？
> > 
> > 
> > 请问Release里面的.exe文件是已经更新的么
> 
> exe 无需更新

非常感谢，已经可以下载了。

**Comment by AdorableStar** [comment]
还有一个问题想请问一下，获取到m3u8文件之后，但是课程体验期结束了，还能继续下载么？

**Comment by cildhdi** [comment]
> 还有一个问题想请问一下，获取到m3u8文件之后，但是课程体验期结束了，还能继续下载么？

没有测试过，建议尽快下载吧
